version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: dockerfile.pipe
    image: tfx_airflow
    ports:
      - 8080:8080
    volumes:
      - ${MODEL_PATH}/iris:/app/models/iris

  server:
    build:
      context: .
      dockerfile: dockerfile.server
    image: tfx_server
    ports:
      - 8000:8000
    volumes:
      - ${MODEL_PATH}/iris:/app/models/iris

volumes:
  iris: {}
