FROM python:3.9

WORKDIR /app

COPY requirements.server.txt .
COPY app/ .

ENV MODEL_PATH "models/iris"

RUN pip install --no-cache-dir -r requirements.server.txt
RUN mkdir -p $MODEL_PATH

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
